site-general-control: true  # 全站开关（true/false），默认开启true，维护时false

# 报名通道开关（为确保功能正常，两个变量请写同一个值，不要出现一个true一个false）
sign-up-button: true  # 首页报名按钮开关，true为打开，false为关闭（默认关闭）
sign-up-control: false  # 落地页开关，true为打开，false为关闭（默认关闭）

top-scroll-bar-control: true  # 顶部循环字条显示/隐藏（true/false）
top-scroll-bar: "🔈 欢迎访问EthanKent的个人博客！网站初期建设正稳步推进，更多精彩，敬请期待！"  # 字条内容

# 左侧广告飘窗设置
floating-window-control: true  # 广告总开关（默认关闭,true/false）
floating-window-img: "https://img.cdn1.vip/i/69edebcea7476_1777200078.webp"    # 广告图片路径，没有则填none
floating-window-content: "<b>广告内容测试</b><br>>>点击进入"  # 广告文字内容
floating-window-link: "/dymun"      # 跳转链接内容

# 超链接模板：<a href="https://example.com">点击这里访问示例网站</a>

# site_run_time: 2025-03-23T09:23:46  # 本次开始运行日期和时间，格式yyyy-mm-ddThh:mm:ss

# site-pv-data-control: -1000  # 全站访问量数据清零（0为实际值）
# site-uv-data-control: -20  # 全站访客数数据清零（0为实际值）

# Site settings
title: EthanKent
SEOTitle: EthanKent
header-img: img/main/header_img.webp
description: "EthanKent的博客"
keyword: "科技,网络,平面设计,艺术,个人博客"
url: "https://ethan-kent.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
# github_repo: "https://github.com/slyzmun/slyzmun.github.io.git" # you code repository

# 以下是联系方式，暂且隐藏
# email是父元素，禁止删除！！！

email: ethankent2007@163.com
QQ: "3204078919"

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "EthanKent"
sidebar-avatar: /img/main/logo.webp      # use absolute URL, seeing it's used in both `/` and `/about/`

# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
# github_username:    qiubaiying
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important

# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk（目前国内无法使用，隐藏）
gitalk:
  enable: false    #是否开启Gitalk评论（true/false）
  clientID: Ov23li3hU3jmJa7cqTbA                            #生成的clientID
  clientSecret: cc5cdc18b164a724d30d980c7efedffab9450727    #生成的clientSecret
  repo: slyzmun_gitalk    #仓库名称
  owner: slyzmun    #github用户名
  admin: ["slyzmun"]
  distractionFreeMode: false #是否启用类似FB的阴影遮罩

# 统计
# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页（建议设置为0）

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# 友情链接
friends: [
    {
#        title: "胜利第一中学",
#        href: "http://www.sldyzx.cn/"
    
#    },{
        title: "云湖社交软件",
        href: "https://www.yhchat.com/"
        
    }
    
]


